# Basic dependabot.yml file with minimum configuration for gomod.

version: 2
updates:
  # Enable version updates for timetrace-gui
  - package-ecosystem: "gomod"
    directory: "/"
    # Check for updates every day (weekdays)
    schedule:
      interval: "weekly"
    target-branch: "develop"
